# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  print_hello:
  # creates the first job
    docker:
      -image: circleci/node:13.8.0
    steps:
      -run:
        name: "Hello"
        command: "echo hello"
  print_world:
    docker:
      -image: circleci/node:13.8.0
    steps:
      -run:
        name: "World"
        command: "echo world"
  

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  welcome:
    -welcome/run
    -print_hello
    -print_world:
      requres:
        - print_hello